### ISSUE TITLE
Clean up the New Maintenance Todo Dialog

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#2]
- [x] Ensure consistent styling
- [x] Remove excess button
- [x] Make it clear somehow that due mileage and due date don't both have to be filled out
