### ISSUE TITLE
Establish theming for Maintenance Todo Cards

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#3]
- [x] make selection check boxes work
- [x] Differentiate Title text and other text
- [x] Button set for edit, delete, etc.
- [x] Due date/mileage theming
