### ISSUE TITLE
Send an email reminder when a todo is due soon

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#369]
Should be a similar screenflow to the mobile app.

**Comment by baylessj** [comment]
- [x] handle singular case for one todo due
- [x] html with plain-text fallback https://stackoverflow.com/questions/3005080/how-to-send-html-email-with-django-with-dynamic-content-in-it
- [x] set up cron job https://devcenter.heroku.com/articles/scheduling-custom-django-management-commands

**Comment by baylessj** [comment]
- [x] Also need to send off an email when an odomsnapshot is added and the mileage makes a todo due soon now

**Comment by baylessj** [comment]
- [x] add rate limits to the emails on snapshot change somehow
