### ISSUE TITLE
Verify Core Functionality

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#83]
From the wiki's Test Plan page.

Basic Functionality Test to ensure that primary user interactions with the app don't get broken by updates and, currently, that basic functionality works in the first place.

# User Sign In/Sign Up

- [x] A User can sign up with a new account.
- [x] A User can sign into an existing account.
- [x] A User can delete their account. - #84

# ToDos

- [x] A new ToDo can be created with all of the available fields filled and the ToDo item will appear in the queue of upcoming ToDo items. - #85
- [x] The contents of an existing ToDo item can be updated, and will be visible when returning to the home screen. - #86
- [x] A ToDo item may be marked as complete.
- [x] A ToDo item may be deleted.

# Repeats

- [x] The default set of repeats are visible after creating a new User account
- [x] Upcoming ToDo items are created for each repeat.
- [x] Repeats can be created, and an associated ToDo item will be created accordingly. - #87
- [x] Repeats can be edited, and their associated ToDo will update accordingly - #89
- [x] Repeats can be deleted, and their associated upcoming ToDo will be deleted accordingly.  - #90

# Refuelings

- [x] New refuelings can be created, and the mileage stored for the associated car will update accordingly. (well enough, #91 covers an edge case)
- [x] A refueling can be edited, and the car mileage will be updated if the edited refueling is the latest refueling post-edit.
- [x] Refuelings can be deleted, and the car mileage will be reverted to its prior state if the deleted refueling was the latest refueling.
